### ISSUE TITLE
Misleading info log: "Could not read active container configuration: null"

### ISSUE THREAD

**Issue by gallardo** [arquillian/arquillian_deprecated#43]
If <code>arquillian.launch</code> property is not defined, arquillian logs the above mentioned message.

I had to examine arquillians' code to realize that arquillian was indeed properly reading the configuration for the container. The message is misleading and I'd suggest to, at least, test that the property is not null to provide an extra hint in the log: <code>Could not read active container configuration: arquillian.launch property not defined</code>

Method: <code>org.jboss.arquillian.impl.client.container.ContainerRegistryCreator.getActivatedConfiguration</code>

**Comment by mojavelinux** [comment]
Could you add this to JIRA if it's still an issue? We aren't using the github issue tracker for Arquillian issues.

https://issues.jboss.org/browse/ARQ

Thanks.

**Comment by gallardo** [comment]
I'm sorry, but it has been a long time without using arquillian, and I cannot afford to test it again for the moment... Thus, I don't have anything against closing the bug, if this is wanted.

**Comment by mojavelinux** [comment]
I think I have enough information to transfer it over. Thanks for replying.
